/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rainbowtableguifinal;

import java.lang.Math;
/**
 *
 * @author paddy
 */
public class Gui extends javax.swing.JFrame {

    /**
     * Creates new form Gui
     */
    private String charset;
    private int num_cols;
    private int num_rows;
    private int pw_length;
    private double pwsp;
    private double ratio;
    
    private RainBowAttackImplementation table; 
    
    public Gui() {
        initComponents();
        
        rbCols.setSelected(true);
        rbRows.setSelected(false);
        charset = "0123456789";        
        num_cols = 40;
        ratio = 1.3;
        pw_length = 4;
        pwsp = Math.pow(charset.length(), pw_length);
        //cols * rows = ratio * pwsp 
        num_rows = (int)(ratio * pwsp / num_cols);
        lbRows.setText(String.valueOf(num_rows) + " Rows");
        lbCols.setText(String.valueOf(num_cols) + " Columns");
        

        RainBowAttackImplementation table = new RainBowAttackImplementation(charset, 3, 50, 40);
        //JavaApplication3 table = new RainBowAttackImplementation(charset, 5, 5000, 125000);

        // Generate the table
        table.generate();

        // Perform a lookup
        //String pass = table.lookup("86f7e437faa5a7fce15d1ddcb9eaeaea377667b8");
        //String pass = table.lookup("052bd5b02559d1270866c5626538e720cec0c135");
        //String pass = table.lookup("7b52009b64fd0a2a49e6d8a939753077792b0554");
        //System.out.println("lookup: " + pass);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btClearSetTableOptions = new javax.swing.JButton();
        btClearUseOptions = new javax.swing.JButton();
        btGenerateTable = new javax.swing.JButton();
        btSearchTableForHash = new javax.swing.JButton();
        tfEnterHash = new javax.swing.JTextField();
        tfPwlen = new javax.swing.JTextField();
        tfCols = new javax.swing.JTextField();
        tfRatio = new javax.swing.JTextField();
        tfRows = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        taGenTable = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        taUseTable = new javax.swing.JTextArea();
        lbWarning = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btSetPwlen = new javax.swing.JButton();
        btSetRatio = new javax.swing.JButton();
        rbCols = new javax.swing.JRadioButton();
        rbRows = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        lbRows = new javax.swing.JLabel();
        lbCols = new javax.swing.JLabel();
        btSetManual = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lbPwlen = new javax.swing.JLabel();

        jButton4.setText("jButton4");

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btClearSetTableOptions.setText("Clear");
        btClearSetTableOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClearSetTableOptionsActionPerformed(evt);
            }
        });

        btClearUseOptions.setText("Clear");
        btClearUseOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClearUseOptionsActionPerformed(evt);
            }
        });

        btGenerateTable.setText("Generate");
        btGenerateTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGenerateTableActionPerformed(evt);
            }
        });

        btSearchTableForHash.setText("Search");
        btSearchTableForHash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSearchTableForHashActionPerformed(evt);
            }
        });

        tfEnterHash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEnterHashActionPerformed(evt);
            }
        });

        tfCols.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfColsActionPerformed(evt);
            }
        });

        tfRatio.setText("ratio");
        tfRatio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfRatioActionPerformed(evt);
            }
        });

        taGenTable.setColumns(20);
        taGenTable.setRows(5);
        jScrollPane1.setViewportView(taGenTable);

        taUseTable.setColumns(20);
        taUseTable.setRows(5);
        jScrollPane3.setViewportView(taUseTable);

        lbWarning.setText("    ");

        jLabel1.setText("Set password length:");

        jLabel2.setText("Enforce Ratio:");

        jLabel3.setText("Set Manual:");

        btSetPwlen.setText("Set");
        btSetPwlen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSetPwlenActionPerformed(evt);
            }
        });

        btSetRatio.setText("Apply ratio");
        btSetRatio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSetRatioActionPerformed(evt);
            }
        });

        rbCols.setText("Cols");
        rbCols.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbColsActionPerformed(evt);
            }
        });

        rbRows.setText("Rows");
        rbRows.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbRowsActionPerformed(evt);
            }
        });

        jLabel4.setText("(Based on)");

        lbRows.setText("rows");

        lbCols.setText("columns");

        btSetManual.setText("Set");
        btSetManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSetManualActionPerformed(evt);
            }
        });

        jLabel5.setText("Enter hash:");

        lbPwlen.setText("Chars");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfPwlen, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btSetPwlen)
                                .addGap(18, 18, 18)
                                .addComponent(lbPwlen)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbCols)
                                .addGap(18, 18, 18)
                                .addComponent(rbRows))
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfRatio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btSetRatio))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btClearSetTableOptions)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btGenerateTable))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfCols, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                                    .addComponent(tfRows))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbRows)
                                    .addComponent(lbCols)))
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btSetManual)))
                        .addGap(126, 126, 126)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btSearchTableForHash)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btClearUseOptions))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfEnterHash))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbWarning)
                        .addGap(312, 312, 312))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPwlen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSetPwlen)
                    .addComponent(lbPwlen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbCols)
                    .addComponent(rbRows))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfRatio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btSetRatio))
                    .addComponent(jLabel5))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(135, 135, 135)
                            .addComponent(lbWarning))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(btSetManual)
                                        .addComponent(tfEnterHash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(7, 7, 7)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(tfRows, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbRows))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(tfCols, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbCols))
                                    .addGap(18, 18, 18))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btSearchTableForHash)
                                        .addComponent(btClearUseOptions))
                                    .addGap(37, 37, 37)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btGenerateTable)
                                .addComponent(btClearSetTableOptions))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btGenerateTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGenerateTableActionPerformed
        try
        {
            table = new RainBowAttackImplementation(charset, pw_length, num_cols, num_rows);
            taGenTable.setText("Password length: " + String.valueOf(pw_length) + "\nRows: " + String.valueOf(num_rows)
                    + "\nColumns" + String.valueOf(num_cols) + "\n\nSuccess");
            
            table.generate();
        }
        catch(Exception e)
        {
            taGenTable.setText("Something went wrong");
            lbWarning.setText("Error: invalid inputs, please try again");
        }
    }//GEN-LAST:event_btGenerateTableActionPerformed

    private void btClearSetTableOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClearSetTableOptionsActionPerformed
        tfPwlen.setText("");
        tfCols.setText("");
        tfRows.setText("");
        tfRatio.setText("");
    }//GEN-LAST:event_btClearSetTableOptionsActionPerformed

    private void tfRatioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfRatioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfRatioActionPerformed

    private void btSetPwlenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSetPwlenActionPerformed
        try
        {
            pw_length = Integer.parseInt(tfPwlen.getText());
            lbPwlen.setText(String.valueOf(pw_length) + " Chars");
        }
        catch (Exception e)
        {
            lbWarning.setText("Error: invalid input");
        }
    }//GEN-LAST:event_btSetPwlenActionPerformed

    private void btSetRatioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSetRatioActionPerformed
        try
        {
            double ratio = Double.parseDouble(tfRatio.getText());
            double pwsp = Math.pow(charset.length(), pw_length);
            
            if (rbRows.isSelected())
            {
                //cols * rows = ratio * pwsp 
                num_cols = (int)(ratio * pwsp / num_rows);
                lbCols.setText(String.valueOf(num_cols) + " Columns");
            }
            else if (rbCols.isSelected())
            {
                //cols * rows = ratio * pwsp 
                num_rows = (int)(ratio * pwsp / num_cols);
                lbRows.setText(String.valueOf(num_rows) + " Rows");

            }
            //ratio = Integer.parseInt(tfPwlen.getText());
        }
        catch (Exception e)
        {
            lbWarning.setText("Error: invalid input");
        }
    }//GEN-LAST:event_btSetRatioActionPerformed

    private void rbColsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbColsActionPerformed
        
        if (rbCols.isSelected())
        {
            rbRows.setSelected(false);
        }
    }//GEN-LAST:event_rbColsActionPerformed

    private void rbRowsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbRowsActionPerformed
        
        if (rbRows.isSelected())
        {
            rbCols.setSelected(false);
        }
    }//GEN-LAST:event_rbRowsActionPerformed

    private void btSetManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSetManualActionPerformed
        try
        {
            num_rows = Integer.parseInt(tfRows.getText());
            num_cols = Integer.parseInt(tfCols.getText());
            
            lbRows.setText(String.valueOf(num_rows));
            lbCols.setText(String.valueOf(num_cols));
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_btSetManualActionPerformed

    private void tfColsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfColsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfColsActionPerformed

    private void btSearchTableForHashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSearchTableForHashActionPerformed
        try
        {
            System.out.println("Searching");
            String result = table.lookup(tfEnterHash.getText());
            System.out.println("Finished!");
            if (result != null)
            {
                taUseTable.setText("Password: " + result); 
            }
            else 
            {
                taUseTable.setText("Could not find password"); 
            }

        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_btSearchTableForHashActionPerformed

    private void tfEnterHashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEnterHashActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEnterHashActionPerformed

    private void btClearUseOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClearUseOptionsActionPerformed
        tfEnterHash.setText("");
        taUseTable.setText("");
    }//GEN-LAST:event_btClearUseOptionsActionPerformed

    
    /*----------------------------Helpers--------------------------------
    -------------------------------------------------------------------*/

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btClearSetTableOptions;
    private javax.swing.JButton btClearUseOptions;
    private javax.swing.JButton btGenerateTable;
    private javax.swing.JButton btSearchTableForHash;
    private javax.swing.JButton btSetManual;
    private javax.swing.JButton btSetPwlen;
    private javax.swing.JButton btSetRatio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbCols;
    private javax.swing.JLabel lbPwlen;
    private javax.swing.JLabel lbRows;
    private javax.swing.JLabel lbWarning;
    private javax.swing.JRadioButton rbCols;
    private javax.swing.JRadioButton rbRows;
    private javax.swing.JTextArea taGenTable;
    private javax.swing.JTextArea taUseTable;
    private javax.swing.JTextField tfCols;
    private javax.swing.JTextField tfEnterHash;
    private javax.swing.JTextField tfPwlen;
    private javax.swing.JTextField tfRatio;
    private javax.swing.JTextField tfRows;
    // End of variables declaration//GEN-END:variables
}
